# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddEmployeers.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import pypyodbc
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddEmployeers(object):
    def setupUi(self, AddEmployeers):
        AddEmployeers.setObjectName("AddEmployeers")
        AddEmployeers.resize(375, 337)
        self.centralwidget = QtWidgets.QWidget(AddEmployeers)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(170, 70, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(170, 110, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(170, 150, 113, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(170, 190, 113, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 70, 91, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 110, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 150, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(80, 190, 47, 13))
        self.label_4.setObjectName("label_4")
        self.okButton = QtWidgets.QPushButton(self.centralwidget)
        self.okButton.setGeometry(QtCore.QRect(140, 250, 75, 23))
        self.okButton.setObjectName("okButton")
        AddEmployeers.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AddEmployeers)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 375, 21))
        self.menubar.setObjectName("menubar")
        AddEmployeers.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AddEmployeers)
        self.statusbar.setObjectName("statusbar")
        AddEmployeers.setStatusBar(self.statusbar)

        self.retranslateUi(AddEmployeers)
        QtCore.QMetaObject.connectSlotsByName(AddEmployeers)

    def okbutton(self):
        try:
            connection = pypyodbc.connect('Driver={SQL Server};'
                                          'Server=WIN-P66F1JER45H\SQLEXPRESS01;'
                                          'Database=rzd;')
            serialofdocuments = self.lineEdit.text()
            lastname = self.lineEdit_2.text()
            firstname = self.lineEdit_3.text()
            position = self.lineEdit_4.text()
            cursor = connection.cursor()
            sqlquery = "INSERT INTO Employess ([Серия паспорта], Фамилия, Имя, Должность) VALUES ('" + serialofdocuments + \
                       "', '" + lastname + "', '" + firstname + "', '" + position + "')"
            cursor.execute(sqlquery)
            connection.commit()
            connection.close()
        except:
            pass

    def retranslateUi(self, AddEmployeers):
        _translate = QtCore.QCoreApplication.translate
        AddEmployeers.setWindowTitle(_translate("AddEmployeers", "MainWindow"))
        self.label.setText(_translate("AddEmployeers", "Серия паспорта"))
        self.label_2.setText(_translate("AddEmployeers", "Фамилия"))
        self.label_3.setText(_translate("AddEmployeers", "Имя"))
        self.label_4.setText(_translate("AddEmployeers", "Должность"))
        self.okButton.setText(_translate("AddEmployeers", "OK"))