# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddTypeOfSensors.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import pypyodbc
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddTypeOfSensors(object):
    def setupUi(self, AddTypeOfSensors):
        AddTypeOfSensors.setObjectName("AddTypeOfSensors")
        AddTypeOfSensors.resize(430, 367)
        self.centralwidget = QtWidgets.QWidget(AddTypeOfSensors)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(220, 70, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(220, 110, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(220, 150, 113, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 70, 61, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 110, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 150, 47, 13))
        self.label_3.setObjectName("label_3")
        self.okButton = QtWidgets.QPushButton(self.centralwidget)
        self.okButton.setGeometry(QtCore.QRect(200, 250, 75, 23))
        self.okButton.setObjectName("okButton")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(220, 190, 113, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(120, 190, 47, 13))
        self.label_4.setObjectName("label_4")
        AddTypeOfSensors.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AddTypeOfSensors)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 430, 21))
        self.menubar.setObjectName("menubar")
        AddTypeOfSensors.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AddTypeOfSensors)
        self.statusbar.setObjectName("statusbar")
        AddTypeOfSensors.setStatusBar(self.statusbar)

        self.retranslateUi(AddTypeOfSensors)
        QtCore.QMetaObject.connectSlotsByName(AddTypeOfSensors)

    def okbutton(self):
        try:
            connection = pypyodbc.connect('Driver={SQL Server};'
                                          'Server=WIN-P66F1JER45H\SQLEXPRESS01;'
                                          'Database=rzd;')
            purpose = self.lineEdit.text()
            type = self.lineEdit_2.text()
            volt = self.lineEdit_3.text()
            station = self.lineEdit_4.text()
            cursor = connection.cursor()
            sqlquery = "INSERT INTO TypeOfSensors (Назначение, Тип, Вольтаж, Станция) VALUES ('" + purpose + \
                       "', '" + type + "', '" + volt + "', '" + station + "')"
            cursor.execute(sqlquery)
            connection.commit()
            connection.close()
        except:
            pass

    def retranslateUi(self, AddTypeOfSensors):
        _translate = QtCore.QCoreApplication.translate
        AddTypeOfSensors.setWindowTitle(_translate("AddTypeOfSensors", "MainWindow"))
        self.label.setText(_translate("AddTypeOfSensors", "Назначение"))
        self.label_2.setText(_translate("AddTypeOfSensors", "Тип"))
        self.label_3.setText(_translate("AddTypeOfSensors", "Вольтаж"))
        self.okButton.setText(_translate("AddTypeOfSensors", "ОК"))
        self.label_4.setText(_translate("AddTypeOfSensors", "Станция"))
