# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditEmployeers.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import pypyodbc
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditEmployeers(object):
    def setupUi(self, EditEmployeers):
        EditEmployeers.setObjectName("EditEmployeers")
        EditEmployeers.resize(375, 337)
        self.centralwidget = QtWidgets.QWidget(EditEmployeers)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(170, 70, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(170, 110, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(170, 150, 113, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(170, 190, 113, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 70, 91, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 110, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 150, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(80, 190, 61, 16))
        self.label_4.setObjectName("label_4")
        self.okButton = QtWidgets.QPushButton(self.centralwidget)
        self.okButton.setGeometry(QtCore.QRect(140, 250, 75, 23))
        self.okButton.setObjectName("okButton")
        EditEmployeers.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(EditEmployeers)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 375, 21))
        self.menubar.setObjectName("menubar")
        EditEmployeers.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(EditEmployeers)
        self.statusbar.setObjectName("statusbar")
        EditEmployeers.setStatusBar(self.statusbar)

        self.retranslateUi(EditEmployeers)
        QtCore.QMetaObject.connectSlotsByName(EditEmployeers)

    def retranslateUi(self, EditEmployeers):
        _translate = QtCore.QCoreApplication.translate
        EditEmployeers.setWindowTitle(_translate("EditEmployeers", "MainWindow"))
        self.label.setText(_translate("EditEmployeers", "Серия паспорта"))
        self.label_2.setText(_translate("EditEmployeers", "Фамилия"))
        self.label_3.setText(_translate("EditEmployeers", "Имя"))
        self.label_4.setText(_translate("EditEmployeers", "Должность"))
        self.okButton.setText(_translate("EditEmployeers", "OK"))

    def okbutton(self, serialkey):
        try:
            connection = pypyodbc.connect('Driver={SQL Server};'
                                          'Server=WIN-P66F1JER45H\SQLEXPRESS01;'
                                          'Database=rzd;')
            serial = self.lineEdit.text()
            lastname = self.lineEdit_2.text()
            firstname = self.lineEdit_3.text()
            position = self.lineEdit_4.text()
            cursor = connection.cursor()
            sqlquery = "UPDATE Employess SET [Серия паспорта] = '" + serial + "', Фамилия = '" + lastname + "', Имя = '"\
                       + firstname + "', Должность = '" + position + "' WHERE [Серия паспорта] = '" + serialkey + "'"
            cursor.execute(sqlquery)
            connection.commit()
            connection.close()
        except:
            pass