# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditStation.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import pypyodbc
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditStation(object):
    def setupUi(self, EditStation):
        EditStation.setObjectName("EditStation")
        EditStation.resize(402, 328)
        self.centralwidget = QtWidgets.QWidget(EditStation)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(160, 100, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 140, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(160, 180, 113, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 100, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 140, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 180, 71, 16))
        self.label_3.setObjectName("label_3")
        self.okButton = QtWidgets.QPushButton(self.centralwidget)
        self.okButton.setGeometry(QtCore.QRect(150, 250, 75, 23))
        self.okButton.setObjectName("okButton")
        EditStation.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(EditStation)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 402, 21))
        self.menubar.setObjectName("menubar")
        EditStation.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(EditStation)
        self.statusbar.setObjectName("statusbar")
        EditStation.setStatusBar(self.statusbar)

        self.retranslateUi(EditStation)
        QtCore.QMetaObject.connectSlotsByName(EditStation)

    def retranslateUi(self, EditStation):
        _translate = QtCore.QCoreApplication.translate
        EditStation.setWindowTitle(_translate("EditStation", "MainWindow"))
        self.label.setText(_translate("EditStation", "Станция"))
        self.label_2.setText(_translate("EditStation", "Участок"))
        self.label_3.setText(_translate("EditStation", "Координаты"))
        self.okButton.setText(_translate("EditStation", "OK"))

    def okbutton(self, stationkey):
        try:
            connection = pypyodbc.connect('Driver={SQL Server};'
                                          'Server=WIN-P66F1JER45H\SQLEXPRESS01;'
                                          'Database=rzd;')
            station = self.lineEdit.text()
            line = self.lineEdit_2.text()
            coordinates = self.lineEdit_3.text()
            cursor = connection.cursor()
            sqlquery = "UPDATE Station SET Станция = '" + station + "', Участок = '" + line + "', Координаты = '"\
                       + coordinates + "' WHERE Станция = '" + stationkey + "'"
            cursor.execute(sqlquery)
            connection.commit()
            connection.close()
        except:
            pass
