# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditTypeOfSensors.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import pypyodbc
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditTypeOfSensors(object):
    def setupUi(self, EditTypeOfSensors):
        EditTypeOfSensors.setObjectName("EditTypeOfSensors")
        EditTypeOfSensors.resize(430, 367)
        self.centralwidget = QtWidgets.QWidget(EditTypeOfSensors)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(220, 70, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(220, 110, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(220, 150, 113, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 70, 61, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 110, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 150, 47, 13))
        self.label_3.setObjectName("label_3")
        self.okButton = QtWidgets.QPushButton(self.centralwidget)
        self.okButton.setGeometry(QtCore.QRect(200, 250, 75, 23))
        self.okButton.setObjectName("okButton")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(220, 190, 113, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(120, 190, 47, 13))
        self.label_4.setObjectName("label_4")
        EditTypeOfSensors.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(EditTypeOfSensors)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 430, 21))
        self.menubar.setObjectName("menubar")
        EditTypeOfSensors.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(EditTypeOfSensors)
        self.statusbar.setObjectName("statusbar")
        EditTypeOfSensors.setStatusBar(self.statusbar)

        self.retranslateUi(EditTypeOfSensors)
        QtCore.QMetaObject.connectSlotsByName(EditTypeOfSensors)

    def retranslateUi(self, EditTypeOfSensors):
        _translate = QtCore.QCoreApplication.translate
        EditTypeOfSensors.setWindowTitle(_translate("EditTypeOfSensors", "MainWindow"))
        self.label.setText(_translate("EditTypeOfSensors", "Назначение"))
        self.label_2.setText(_translate("EditTypeOfSensors", "Тип"))
        self.label_3.setText(_translate("EditTypeOfSensors", "Вольтаж"))
        self.okButton.setText(_translate("EditTypeOfSensors", "ОК"))
        self.label_4.setText(_translate("EditTypeOfSensors", "Станция"))

    def okbutton(self, typekey, stationkey):
        try:
            connection = pypyodbc.connect('Driver={SQL Server};'
                                          'Server=WIN-P66F1JER45H\SQLEXPRESS01;'
                                          'Database=rzd;')
            purpose = self.lineEdit.text()
            type = self.lineEdit_2.text()
            volt = self.lineEdit_3.text()
            station = self.lineEdit_4.text()
            cursor = connection.cursor()
            sqlquery = "UPDATE TypeOfSensors SET Назначение = '" + purpose + "', Тип = '" + type + "', Вольтаж = '"\
                       + volt + "', Станция = '" + station + "' WHERE Тип = '" + typekey + "' AND Станция = '" + stationkey + "'"
            cursor.execute(sqlquery)
            connection.commit()
            connection.close()
        except:
            pass